version: '3.8'
services:
  backend:
    build: .
    container_name: se-backend-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - se_network

networks:
  se_network:
    external: true
